import React, { useState, useEffect } from 'react';
import '../index.css';
import { useT } from '../i18n';

const { ipcRenderer } = window.require('electron');

const TERMS_TEXT_JA = `MOZ-3 Quick Shot (QS) 利用規約

第1条（目的）
本規約は、モタロ（以下「開発者」）が提供するソフトウェア「MOZ-3 Quick Shot」（以下「本アプリ」）の利用条件を定めるものです。
ユーザーは本アプリをインストールまたは利用することで、本規約に同意したものとみなされます。

第2条（ライセンスの許諾と権利の帰属）

開発者は、ユーザーに対し、本アプリを自身の端末にインストールし、私的または商用目的（動画制作、サムネイル作成、資料作成等）で利用する非独占的な権利を許諾します。

本アプリ自体の著作権、プログラム、および関連する知的財産権は、すべて開発者に帰属します。

第3条（商用利用および著作物の取り扱い）

本アプリを用いた加工画像の商用利用は許可されていますが、これは本アプリの機能を利用して「ユーザー自身のオリジナル作品」や「商用利用が許可されている素材」を商用利用することを認めるものです。

第三者が著作権、肖像権、商標権等の権利を有する画像（アニメ、映画、他者のイラスト、写真などを含む）を本アプリで加工し、無断で販売、配布、またはその他の商用目的で利用する行為は固く禁じます。

本アプリで取り扱う画像の利用にあたっては、ユーザー自身の責任において、各画像データの権利元が定める利用規約やプライバシーポリシー、ガイドラインを必ず遵守してください。ユーザーによる権利侵害行為について、開発者は一切の責任を負いません。

第4条（完全ローカル処理とプライバシー保護）

本アプリの画像処理（背景透過、アップスケール等）は、すべてユーザーのPC端末内（ローカル環境）で完結します。

開発者がユーザーの画像データを外部サーバーへ送信・アップロードすることや、無断でデータ収集・解析を行うことは一切ありません。ユーザーは自身のプライバシーとデータを保護された状態で本アプリを安心してご利用いただけます。

第5条（禁止事項）
ユーザーは、以下の行為を行ってはなりません。

本アプリの解析（リバースエンジニアリング）、改変、または二次配布。

第3条に違反する、他者の権利（著作権等）を侵害する目的での本アプリの利用。

本アプリの名称や、開発者およびそれに付随するキャラクターのイメージを著しく損なう形での利用。

第6条（免責事項）

動作保証： 開発者は、本アプリがあらゆる環境で正常に動作すること、およびバグがないことを完全には保証しません。

データの損失等： 本アプリの利用により生じたデータの損失、PCの不具合、その他の損害について、開発者は一切の責任を負いません。

処理機能の結果： 独自の画像解析テクノロジー等による処理結果の正確性や品質について、開発者は完全な保証を行うものではありません。

第7条（アップデートとサポート）

開発者は、ユーザーに事前に通知することなく本アプリのアップデート、仕様変更、または提供の停止を行うことができます。

本アプリに関するサポートは開発者の任意であり、すべての問い合わせへの回答や対応を保証するものではありません。

💡 開発者からのお願い
本アプリを気に入ってくださった方は、開発者モタロのYouTubeチャンネル登録、Twitter（X）のフォロー、そして周りのクリエイターへのアプリの共有・拡散をお願いします！皆さんの応援が開発のモチベーションになります！`;

const TERMS_TEXT_EN = `MOZ-3 Quick Shot (QS) Terms of Service

Article 1 (Purpose and Acceptance)
These Terms of Service (hereinafter referred to as the "ToS") establish the conditions for using the software "MOZ-3 Quick Shot" (hereinafter referred to as the "App") provided by Motaro (hereinafter referred to as the "Developer").
By installing or using the App, the user is deemed to have agreed to this ToS.

Article 2 (License Grant and Intellectual Property Rights)

The Developer grants the user a non-exclusive right to install the App on their own device and use it for personal or commercial purposes (e.g., video production, thumbnail creation, document preparation).

All copyrights, programs, and related intellectual property rights of the App itself belong exclusively to the Developer.

Article 3 (Commercial Use and Copyright Compliance)

Commercial use of images processed using the App is permitted, provided that the user is utilizing the App's features to commercially use their "own original works" or "materials explicitly permitted for commercial use."

Processing images to which third parties hold rights (including copyrights, portrait rights, and trademark rights—such as anime, movies, other creators' illustrations, and photographs) using the App, and subsequently selling, distributing, or otherwise using them for commercial purposes without authorization, is strictly prohibited.

When using images within the App, it is the user's sole responsibility to strictly comply with the terms of use, privacy policies, and guidelines established by the respective rights holders of each image data. The Developer shall not be held liable for any copyright infringement or related violations committed by the user.

Article 4 (Fully Local Processing and Privacy Protection)

All image processing functions of the App (such as background removal, upscaling, etc.) are executed entirely within the user's PC (local environment).

The Developer will never send, upload, or collect user image data to external servers, nor will the Developer perform unauthorized data analysis. Users can confidently use the App with their privacy and data fully protected.

Article 5 (Prohibited Conduct)
Users must not engage in any of the following acts:

Reverse engineering, modifying, or unauthorized secondary distribution of the App.

Using the App for the purpose of infringing on the rights (e.g., copyrights) of others, in violation of Article 3.

Using the App in a manner that significantly damages the reputation or image of the App, the Developer, or associated characters.

Article 6 (Disclaimer of Warranties and Liability)

No Warranty of Operation: The Developer does not guarantee that the App will operate normally in all environments or that it is entirely free of bugs.

Data Loss, etc.: The Developer shall not be held responsible for any data loss, PC malfunctions, or other damages resulting from the use of the App.

Processing Results: The Developer makes no absolute guarantees regarding the accuracy or quality of the processing results generated by the proprietary image analysis technology.

Article 7 (Updates and Support)

The Developer reserves the right to update, modify specifications, or suspend the provision of the App at any time without prior notice to the user.

Technical support for the App is provided at the Developer's discretion. The Developer does not guarantee a response or resolution to all inquiries.`;

const YOUTUBE_URL = 'https://t.co/KQjU9dDLR9';

export default function SettingsModal({ onClose, keptCount }) {
    const { t, lang } = useT();
    const [activeTab, setActiveTab] = useState('general');
    const [path, setPath] = useState('');
    const [isDefault, setIsDefault] = useState(true);
    const [autoStart, setAutoStart] = useState(true);
    const [keepAiOpen, setKeepAiOpen] = useState(true);
    const [language, setLanguage] = useState(lang);

    const [hotkeys, setHotkeys] = useState({
        startCapture: '',
        repeatCapture: '',
        showWorkspace: ''
    });
    const [recordingKeyFor, setRecordingKeyFor] = useState(null);

    useEffect(() => {
        ipcRenderer.invoke('get-config').then(cfg => {
            if (cfg.customSavePath) {
                setPath(cfg.customSavePath);
                setIsDefault(false);
            } else {
                setPath('');
                setIsDefault(true);
            }
            if (cfg.hotkeys) setHotkeys(cfg.hotkeys);
            if (cfg.language) setLanguage(cfg.language);
            setKeepAiOpen(cfg.keepAiOpen !== false); // デフォルト true
        });
        ipcRenderer.invoke('get-login-item').then(val => setAutoStart(val));
    }, []);

    // lang が外部から変わったときに同期
    useEffect(() => { setLanguage(lang); }, [lang]);

    const handleChangePath = async () => {
        if (keptCount > 0) {
            const confirmed = await ipcRenderer.invoke('show-confirm-dialog', { message: t('changePathConfirm') });
            if (!confirmed) return;
        }
        const newPath = await ipcRenderer.invoke('select-folder');
        if (newPath) {
            await ipcRenderer.invoke('set-custom-path', newPath);
            setPath(newPath);
            setIsDefault(false);
        }
    };

    const handleResetPath = async () => {
        if (keptCount > 0) {
            const confirmed = await ipcRenderer.invoke('show-confirm-dialog', { message: t('changePathConfirm') });
            if (!confirmed) return;
        }
        await ipcRenderer.invoke('set-custom-path', null);
        setPath('');
        setIsDefault(true);
    };

    const handleAutoStartChange = async (e) => {
        const enabled = e.target.checked;
        setAutoStart(enabled);
        await ipcRenderer.invoke('set-login-item', enabled);
    };

    const handleKeepAiOpenChange = async (e) => {
        const enabled = e.target.checked;
        setKeepAiOpen(enabled);
        await ipcRenderer.invoke('set-keep-ai-open', enabled);
    };

    const handleLanguageChange = async (e) => {
        const newLang = e.target.value;
        setLanguage(newLang);
        await ipcRenderer.invoke('set-language', newLang);
    };

    const handleResetHotkey = async (action) => {
        await ipcRenderer.invoke('set-hotkey', { action, accelerator: '' });
        setHotkeys(prev => ({ ...prev, [action]: '' }));
    };

    useEffect(() => {
        if (!recordingKeyFor) return;
        const handleKeyDown = (e) => {
            e.preventDefault();
            const keys = [];
            if (e.ctrlKey) keys.push('CommandOrControl');
            if (e.altKey) keys.push('Alt');
            if (e.shiftKey) keys.push('Shift');
            if (['Control', 'Alt', 'Shift', 'Meta'].includes(e.key)) return;
            let keyName = e.key.toUpperCase();
            if (e.code.startsWith('Key')) keyName = e.code.replace('Key', '');
            else if (e.code.startsWith('Digit')) keyName = e.code.replace('Digit', '');
            keys.push(keyName);
            const combo = keys.join('+');
            ipcRenderer.invoke('set-hotkey', { action: recordingKeyFor, accelerator: combo }).then(() => {
                setHotkeys(prev => ({ ...prev, [recordingKeyFor]: combo }));
                setRecordingKeyFor(null);
            });
        };
        window.addEventListener('keydown', handleKeyDown);
        return () => window.removeEventListener('keydown', handleKeyDown);
    }, [recordingKeyFor]);

    const TABS = [
        { id: 'general', label: t('tabGeneral') },
        { id: 'hotkeys', label: t('tabHotkeys') },
        { id: 'terms', label: t('tabTerms') },
    ];

    const HOTKEY_ROWS = [
        { key: 'startCapture', label: t('hotkeyCapture') },
        { key: 'repeatCapture', label: t('hotkeyRepeat') },
        { key: 'showWorkspace', label: t('hotkeyWorkspace') },
    ];

    return (
        <div style={{
            position: 'absolute',
            inset: 0,
            background: 'var(--bg-panel)',
            display: 'flex',
            flexDirection: 'column',
            zIndex: 50,
            borderTop: '1px solid var(--border)',
        }}>
            {/* ── Header ── */}
            <div style={{
                padding: '6px 12px',
                borderBottom: '1px solid var(--border)',
                display: 'flex',
                justifyContent: 'space-between',
                alignItems: 'center',
                flexShrink: 0,
            }}>
                <div style={{ fontSize: 13, fontWeight: 700, display: 'flex', alignItems: 'center', gap: 6, color: 'var(--text)' }}>
                    <span style={{ color: 'var(--accent)' }}>⚙</span> {t('settingsTitle')}
                </div>
                <button
                    onClick={onClose}
                    style={{ background: 'none', border: 'none', color: '#00ffff', fontSize: 14, cursor: 'pointer', padding: '4px 8px', lineHeight: 1, fontFamily: 'Inter, system-ui' }}
                    title={t('settingsTitle')}
                >✕</button>
            </div>

            {/* ── Body ── */}
            <div style={{ display: 'flex', flex: 1, overflow: 'hidden' }}>
                {/* Sidebar */}
                <div style={{
                    width: 140, borderRight: '1px solid var(--border)', background: 'rgba(0,0,0,0.2)',
                    display: 'flex', flexDirection: 'column', padding: '12px 6px', gap: 2, flexShrink: 0,
                }}>
                    {TABS.map(tab => (
                        <button
                            key={tab.id}
                            onClick={() => setActiveTab(tab.id)}
                            style={{
                                background: activeTab === tab.id ? 'rgba(0,255,255,0.1)' : 'transparent',
                                color: activeTab === tab.id ? 'var(--accent)' : 'var(--text-sub)',
                                border: 'none', padding: '8px 12px', borderRadius: 6,
                                textAlign: 'left', cursor: 'pointer', fontSize: 12,
                                fontWeight: activeTab === tab.id ? 700 : 400,
                                transition: 'all 0.2s', fontFamily: 'Inter, system-ui',
                            }}
                        >
                            {tab.label}
                        </button>
                    ))}
                </div>

                {/* Content */}
                <div style={{ flex: 1, padding: '20px 24px', overflowY: 'auto' }}>

                    {/* ── 基本設定 ── */}
                    {activeTab === 'general' && (
                        <div style={{ display: 'flex', flexDirection: 'column', gap: 24 }}>

                            {/* 保存先 */}
                            <div>
                                <h3 style={{ fontSize: 13, fontWeight: 700, margin: '0 0 8px 0', color: 'var(--text)' }}>{t('savePathTitle')}</h3>
                                <p style={{ fontSize: 11, color: 'var(--text-sub)', lineHeight: 1.5, margin: '0 0 12px 0' }}>{t('savePathDesc')}</p>
                                <div style={{ display: 'flex', gap: 8, alignItems: 'center' }}>
                                    <div style={{
                                        flex: 1, background: 'rgba(0,0,0,0.3)', border: '1px solid var(--border)', borderRadius: 6,
                                        padding: '7px 10px', fontSize: 11, color: 'var(--text)', fontFamily: 'monospace',
                                        overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap',
                                    }}>
                                        {path || t('savePathDefault')}
                                    </div>
                                    {isDefault ? (
                                        <button onClick={handleChangePath} style={{ background: 'var(--accent)', color: '#000', border: 'none', borderRadius: 6, padding: '7px 14px', fontSize: 11, fontWeight: 700, cursor: 'pointer', whiteSpace: 'nowrap' }}>
                                            {t('changeBtn')}
                                        </button>
                                    ) : (
                                        <button onClick={handleResetPath} style={{ background: 'rgba(255,255,255,0.1)', color: 'var(--text)', border: 'none', borderRadius: 6, padding: '7px 14px', fontSize: 11, fontWeight: 700, cursor: 'pointer', whiteSpace: 'nowrap' }}>
                                            {t('resetBtn')}
                                        </button>
                                    )}
                                </div>
                                {!isDefault && (
                                    <div style={{ marginTop: 8, display: 'inline-block', padding: '3px 8px', background: 'rgba(255,68,102,0.1)', color: '#ff4466', borderRadius: 4, fontSize: 10, border: '1px solid rgba(255,68,102,0.3)' }}>
                                        {t('autoCleanOff')}
                                    </div>
                                )}
                            </div>

                            {/* 起動・表示設定 */}
                            <div style={{ borderTop: '1px solid var(--border)', paddingTop: 20, display: 'flex', flexDirection: 'column', gap: 14 }}>
                                <label style={{ display: 'flex', alignItems: 'flex-start', gap: 10, cursor: 'pointer' }}>
                                    <input type="checkbox" checked={autoStart} onChange={handleAutoStartChange} style={{ accentColor: '#00ffff', width: 14, height: 14, cursor: 'pointer', marginTop: 2, flexShrink: 0 }} />
                                    <span style={{ fontSize: 12, color: 'var(--text)', lineHeight: 1.4 }}>{t('autoStartLabel')}</span>
                                </label>
                                <label style={{ display: 'flex', alignItems: 'flex-start', gap: 10, cursor: 'pointer' }}>
                                    <input type="checkbox" checked={keepAiOpen} onChange={handleKeepAiOpenChange} style={{ accentColor: '#00ffff', width: 14, height: 14, cursor: 'pointer', marginTop: 2, flexShrink: 0 }} />
                                    <span style={{ fontSize: 12, color: 'var(--text)', lineHeight: 1.4 }}>{t('keepAiOpenLabel')}</span>
                                </label>
                            </div>

                            {/* 画像全削除 */}
                            <div style={{ borderTop: '1px solid var(--border)', paddingTop: 20 }}>
                                <h3 style={{ fontSize: 13, fontWeight: 700, margin: '0 0 8px 0', color: 'var(--text)' }}>{t('deleteAllTitle')}</h3>
                                <button
                                    onClick={async () => {
                                        const confirmed = await ipcRenderer.invoke('show-confirm-dialog', { message: t('deleteAllConfirm') });
                                        if (!confirmed) return;
                                        await ipcRenderer.invoke('delete-all-images');
                                    }}
                                    style={{
                                        background: 'rgba(255,68,102,0.12)', border: '1px solid rgba(255,68,102,0.4)',
                                        borderRadius: 6, color: '#ff4466', fontSize: 12, fontWeight: 700,
                                        padding: '7px 18px', cursor: 'pointer', fontFamily: 'Inter, system-ui',
                                        transition: 'all 0.2s',
                                    }}
                                    onMouseEnter={e => { e.currentTarget.style.background = 'rgba(255,68,102,0.22)'; e.currentTarget.style.borderColor = 'rgba(255,68,102,0.7)'; }}
                                    onMouseLeave={e => { e.currentTarget.style.background = 'rgba(255,68,102,0.12)'; e.currentTarget.style.borderColor = 'rgba(255,68,102,0.4)'; }}
                                >
                                    {t('deleteAllBtn')}
                                </button>
                            </div>

                            {/* 言語 */}
                            <div style={{ borderTop: '1px solid var(--border)', paddingTop: 20 }}>
                                <h3 style={{ fontSize: 13, fontWeight: 700, margin: '0 0 10px 0', color: 'var(--text)' }}>{t('languageTitle')}</h3>
                                <select
                                    value={language}
                                    onChange={handleLanguageChange}
                                    style={{
                                        background: 'rgba(0,0,0,0.4)',
                                        border: '1px solid var(--border)',
                                        borderRadius: 6,
                                        color: 'var(--accent)',
                                        fontSize: 12,
                                        padding: '6px 12px',
                                        cursor: 'pointer',
                                        fontFamily: 'Inter, system-ui',
                                        outline: 'none',
                                        minWidth: 160,
                                    }}
                                >
                                    <option value="ja">🇯🇵 日本語</option>
                                    <option value="en">🇺🇸 English</option>
                                </select>
                            </div>
                        </div>
                    )}

                    {/* ── ショートカット ── */}
                    {activeTab === 'hotkeys' && (
                        <div style={{ display: 'flex', flexDirection: 'column', gap: 20 }}>
                            <h3 style={{ fontSize: 13, fontWeight: 700, margin: '0 0 4px 0', color: 'var(--text)' }}>{t('shortcutsTitle')}</h3>
                            {HOTKEY_ROWS.map(({ key, label }, i, arr) => (
                                <div key={key} style={{
                                    display: 'flex', alignItems: 'center', justifyContent: 'space-between',
                                    borderBottom: i < arr.length - 1 ? '1px solid rgba(255,255,255,0.05)' : 'none',
                                    paddingBottom: i < arr.length - 1 ? 16 : 0,
                                }}>
                                    <div style={{ fontSize: 12, color: 'var(--text)' }}>{label}</div>
                                    <div style={{ display: 'flex', gap: 6, alignItems: 'center' }}>
                                        <button
                                            onClick={() => setRecordingKeyFor(recordingKeyFor === key ? null : key)}
                                            style={{
                                                background: recordingKeyFor === key ? 'var(--accent)' : 'rgba(0,0,0,0.3)',
                                                border: '1px solid var(--border)', borderRadius: 4,
                                                color: recordingKeyFor === key ? '#000' : 'var(--accent)',
                                                padding: '5px 14px', fontSize: 11, cursor: 'pointer',
                                                fontFamily: 'monospace', minWidth: 110, textAlign: 'center',
                                            }}
                                        >
                                            {recordingKeyFor === key ? t('hotkeyRecording') : (hotkeys[key] ? hotkeys[key].replace('CommandOrControl', 'Ctrl') : t('hotkeyNotSet'))}
                                        </button>
                                        <button
                                            onClick={() => handleResetHotkey(key)}
                                            style={{
                                                background: 'rgba(255,255,255,0.05)', border: '1px solid var(--border)', borderRadius: 4,
                                                color: 'var(--text-sub)', padding: '5px 10px', fontSize: 10, cursor: 'pointer',
                                                transition: 'all 0.2s', whiteSpace: 'nowrap',
                                            }}
                                            onMouseEnter={e => e.currentTarget.style.color = 'var(--text)'}
                                            onMouseLeave={e => e.currentTarget.style.color = 'var(--text-sub)'}
                                        >
                                            {t('hotkeyReset')}
                                        </button>
                                    </div>
                                </div>
                            ))}
                        </div>
                    )}

                    {/* ── 利用規約 ── */}
                    {activeTab === 'terms' && (
                        <div style={{ display: 'flex', flexDirection: 'column', gap: 16, height: '100%', position: 'relative' }}>
                            {/* 規約テキスト */}
                            <div style={{
                                flex: 1,
                                background: 'rgba(0,0,0,0.35)',
                                border: '1px solid var(--border)',
                                borderRadius: 8,
                                padding: '14px 16px',
                                overflowY: 'auto',
                                fontSize: 11,
                                color: 'var(--text-sub)',
                                lineHeight: 1.8,
                                whiteSpace: 'pre-wrap',
                                minHeight: 0,
                                maxHeight: 260,
                            }}>
                                {lang === 'en' ? TERMS_TEXT_EN : TERMS_TEXT_JA}
                            </div>

                            {/* キャラクターイラスト */}
                            <img
                                src="./picture/motako.png"
                                alt="motako"
                                style={{
                                    position: 'absolute',
                                    bottom: 0,
                                    right: 0,
                                    height: 150,
                                    pointerEvents: 'none',
                                    userSelect: 'none',
                                }}
                            />

                            {/* YouTubeリンク */}
                            <div style={{ display: 'flex', alignItems: 'center', gap: 10, paddingTop: 4 }}>
                                <button
                                    onClick={() => ipcRenderer.send('open-external', YOUTUBE_URL)}
                                    style={{
                                        display: 'flex', alignItems: 'center', gap: 8,
                                        background: 'rgba(255,0,0,0.12)', border: '1px solid rgba(255,0,0,0.35)',
                                        borderRadius: 8, padding: '8px 16px', cursor: 'pointer',
                                        transition: 'all 0.2s',
                                    }}
                                    onMouseEnter={e => { e.currentTarget.style.background = 'rgba(255,0,0,0.22)'; e.currentTarget.style.borderColor = 'rgba(255,0,0,0.6)'; }}
                                    onMouseLeave={e => { e.currentTarget.style.background = 'rgba(255,0,0,0.12)'; e.currentTarget.style.borderColor = 'rgba(255,0,0,0.35)'; }}
                                >
                                    {/* YouTube icon (SVG) */}
                                    <svg width="20" height="14" viewBox="0 0 20 14" fill="none" xmlns="http://www.w3.org/2000/svg">
                                        <path d="M19.6 2.2C19.4 1.4 18.8 0.8 18 0.6C16.4 0.2 10 0.2 10 0.2C10 0.2 3.6 0.2 2 0.6C1.2 0.8 0.6 1.4 0.4 2.2C0 3.8 0 7 0 7C0 7 0 10.2 0.4 11.8C0.6 12.6 1.2 13.2 2 13.4C3.6 13.8 10 13.8 10 13.8C10 13.8 16.4 13.8 18 13.4C18.8 13.2 19.4 12.6 19.6 11.8C20 10.2 20 7 20 7C20 7 20 3.8 19.6 2.2Z" fill="#FF0000"/>
                                        <path d="M8 10L13.2 7L8 4V10Z" fill="white"/>
                                    </svg>
                                    <span style={{ fontSize: 12, color: '#ff4444', fontWeight: 600, fontFamily: 'Inter, system-ui' }}>
                                        {t('termsYoutubeLabel')}
                                    </span>
                                </button>
                            </div>
                        </div>
                    )}

                </div>
            </div>
        </div>
    );
}
